name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build .exe
        run: |
          .venv\Scripts\Activate.ps1
          nicegui-pack --name "AsanaTool" main.py

      - name: Compress
        run: Compress-Archive -Path dist/AsanaTool -DestinationPath dist/AsanaTool.zip
      - uses: actions/upload-artifact@v4
        with:
          name: AsanaTool.zip
          path: dist/AsanaTool.zip
          if-no-files-found: error

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        
      - name: Extract changelog
        run: |
          version=$(echo "${GITHUB_REF#refs/tags/}")
          changelog=$(sed -n '/## '${version}'/,/^## /p' CHANGELOG.md | sed '$d' | tail -n +3)
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$changelog" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - uses: actions/download-artifact@v4
        with:
          name: AsanaTool.zip
          path: ./

      - uses: softprops/action-gh-release@v2
        with:
          body: ${{env.CHANGELOG}}
          files: "./AsanaTool.zip"
          fail_on_unmatched_files: true
